(lang dune 3.11)

(name day2)

(generate_opam_files true)

(package
 (name day2)
 (allow_empty)
 (depends ocaml dune))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
